//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:20:44 PM FET 
//


package android.control;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the android.control package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: android.control
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link App }
     * 
     */
    public App createApp() {
        return new App();
    }

    /**
     * Create an instance of {@link Cyanogen }
     * 
     */
    public Cyanogen createCyanogen() {
        return new Cyanogen();
    }

    /**
     * Create an instance of {@link App.ForceTranslation }
     * 
     */
    public App.ForceTranslation createAppForceTranslation() {
        return new App.ForceTranslation();
    }

    /**
     * Create an instance of {@link App.ForceNotranslation }
     * 
     */
    public App.ForceNotranslation createAppForceNotranslation() {
        return new App.ForceNotranslation();
    }

    /**
     * Create an instance of {@link Translation }
     * 
     */
    public Translation createTranslation() {
        return new Translation();
    }

}
