//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:20:44 PM FET 
//


package android.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the android.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: android.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResXmlStringArray }
     * 
     */
    public ResXmlStringArray createResXmlStringArray() {
        return new ResXmlStringArray();
    }

    /**
     * Create an instance of {@link ResXmlPlurals }
     * 
     */
    public ResXmlPlurals createResXmlPlurals() {
        return new ResXmlPlurals();
    }

    /**
     * Create an instance of {@link ResXmlResources }
     * 
     */
    public ResXmlResources createResXmlResources() {
        return new ResXmlResources();
    }

    /**
     * Create an instance of {@link ResXmlString }
     * 
     */
    public ResXmlString createResXmlString() {
        return new ResXmlString();
    }

    /**
     * Create an instance of {@link ResXmlStringArray.Item }
     * 
     */
    public ResXmlStringArray.Item createResXmlStringArrayItem() {
        return new ResXmlStringArray.Item();
    }

    /**
     * Create an instance of {@link ResXmlPlurals.Item }
     * 
     */
    public ResXmlPlurals.Item createResXmlPluralsItem() {
        return new ResXmlPlurals.Item();
    }

}
