//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.24 at 12:48:17 AM VET 
//


package android.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}string-array" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}plurals" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "string",
    "stringArray",
    "plurals"
})
@XmlRootElement(name = "resources")
public class ResXmlResources {

    protected List<ResXmlString> string;
    @XmlElement(name = "string-array")
    protected List<ResXmlStringArray> stringArray;
    protected List<ResXmlPlurals> plurals;

    /**
     * Gets the value of the string property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the string property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getString().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResXmlString }
     * 
     * 
     */
    public List<ResXmlString> getString() {
        if (string == null) {
            string = new ArrayList<ResXmlString>();
        }
        return this.string;
    }

    /**
     * Gets the value of the stringArray property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stringArray property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStringArray().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResXmlStringArray }
     * 
     * 
     */
    public List<ResXmlStringArray> getStringArray() {
        if (stringArray == null) {
            stringArray = new ArrayList<ResXmlStringArray>();
        }
        return this.stringArray;
    }

    /**
     * Gets the value of the plurals property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the plurals property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlurals().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResXmlPlurals }
     * 
     * 
     */
    public List<ResXmlPlurals> getPlurals() {
        if (plurals == null) {
            plurals = new ArrayList<ResXmlPlurals>();
        }
        return this.plurals;
    }

}
