/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_alex73_android_common_JniWrapper */

#ifndef _Included_org_alex73_android_common_JniWrapper
#define _Included_org_alex73_android_common_JniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_alex73_android_common_JniWrapper
 * Method:    getPermissions
 * Signature: (Lorg/alex73/android/common/FilePerm;)V
 */
JNIEXPORT void JNICALL Java_org_alex73_android_common_JniWrapper_getPermissions
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_alex73_android_common_JniWrapper
 * Method:    getSpaceNearFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_alex73_android_common_JniWrapper_getSpaceNearFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_alex73_android_common_JniWrapper
 * Method:    chmod
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_alex73_android_common_JniWrapper_chmod
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
